### PR TITLE
Simplify code.

### PR DESCRIPTION
**Pull request by dcherian**
Yet another attempt to simplify combine_turbulence.

1. stratification histograms: Only two panels now. Show pdf of dTdz, 2π/N only
2. More descriptive names for flagging masks when printed to screen
3. Move masking histogram plots to ApplyMask (simplify combine_turbulence)
4. Add more comments.

Any thoughts on what else could be simplified? Or what steps are usually confusing?

### CODE REVIEW

**Comment by jbecherer** [comment]
Are we saving all masks in Turb file?? 
That could be really helpful to diagnose after the fact, which mask causes what, besides the pure 
output of combine_turb.

**Comment by dcherian** [comment]
Ya that could be interesting. Maybe count how many times a particular mask was applied in a avgwindow chunk? We could do a stacked histogram with that output like Noel.

**Comment by jbecherer** [comment]
Ahh right... I forgot that we mask on the 1sec time step, which we probably don't want to keep in Turb. 
Maybe even a simple Mask field, that just contains % values for each mask on how often it kicked in?

**Comment by dcherian** [comment]
> Ahh right... I forgot that we mask on the 1sec time step, which we probably don't want to keep in Turb.

We can keep the sum though. I'm doing it now actually.

> Maybe even a simple Mask field, that just contains % values for each mask on how often it kicked in?

That already exists in chi.stats.xxx_percentage :)

**Comment by jbecherer** [comment]
Ah. Ok. I didn't realize that. That's really helpful, if only I would have known earlier :)

**Comment by jbecherer** [comment]
The whole combine_turbulence thing is so power-full. I feel it is just not very well documented.
Most of the stuff one could wish for you already implemented, but besides you hardly anybody 
knows about it :)

**Comment by dcherian** [comment]
Hah, I agree but the percentages were implemented by Sally.

**Comment by dcherian** [comment]
What do you think of this reformatted output from combine_turbulence?

```
----------> adding mm2

    71.7185% chi estimates are NaN before I truncate to valid time limits.
    71.7185% chi estimates are NaN before I start masking.

    ==== Now masking 1 sec averaged estimate.
    N2 < 1.0e-06 NaN-ed out 0.00% of estimates (184 points)
    inst speed (pumping + background) < 5.0e-02 NaN-ed out 0.06% of estimates (19401 points)
    background flow < 5.0e-02 NaN-ed out 0.12% of estimates (42954 points)
    max_chi > 1.0e-03 NaN-ed out 0.00% of estimates (18 points)
    max_eps > 1.0e-02 NaN-ed out 0.01% of estimates (3423 points)
    Deglitch log10(chi)...
deglitch removed 30484 points = 0.3 % | avg(NaNed points) = -8.0e+00 | median(NaNed points) = -7.9e+00
    Deglitch log10(eps)...
deglitch removed 10096 points = 0.1 % | avg(NaNed points) = -8.7e+00 | median(NaNed points) = -9.0e+00
Elapsed time is 5.980644 seconds.
    Is Tp at noise floor? spec_floor_mask = 1.0e+00 zeroed out 49.63% of estimates (17337503 points)
    number of points in final fitting range, n_freq < 3.0e+00 NaN-ed out 17.36% of estimates (6064453 points)
    IC fit for a VC estimate, kstop < ki = 1.0e+00 NaN-ed out 0.00% of estimates (553 points)


    =================================================================
    .... Processing Winters & D'Asaro estimate. Takes 120s for 1 year.
    /home/deepak/work/bay/ebob/data/518/input/dTdz_w.mat not found. 
     Using chi.wda to do Winters & D'Asaro estimate
      WDA: 8284 = 4.2664% time intervals have chi=NaN. 
      WDA: 510 = 0.26266% time intervals did not see enough pumping to make an estimate. 
Elapsed time is 23.123916 seconds.
    =================================================================
    Tz < 3.0e-03 NaN-ed out 0.35% of estimates (123883 points)

    Running moving average
    Summing up masks...
Elapsed time is 3.672776 seconds.

    ==== Now masking 600 sec averaged estimate.
    avg dTdz < 3.0e-03 NaN-ed out 0.14% of estimates (81 points)
    |Tz| going below threshold = 1.0e+00 NaN-ed out 0.47% of estimates (271 points)
    max_Kt > 1.0e+00 NaN-ed out 0.00% of estimates (0 points)
    max_Jq > 1.0e+04 NaN-ed out 0.00% of estimates (0 points)

----------> adding mm2_ic

    0.074289% chi estimates are NaN before I truncate to valid time limits.
    0.074289% chi estimates are NaN before I start masking.

    ==== Now masking 1 sec averaged estimate.
    N2 < 1.0e-06 NaN-ed out 0.00% of estimates (1 points)
    inst speed (pumping + background) < 5.0e-02 NaN-ed out 2.32% of estimates (1342 points)
    background flow < 5.0e-02 NaN-ed out 2.49% of estimates (1439 points)
    max_chi > 1.0e-03 NaN-ed out 0.02% of estimates (10 points)
    max_eps > 1.0e-02 NaN-ed out 0.05% of estimates (30 points)
    Tz < 3.0e-03 NaN-ed out 0.27% of estimates (154 points)

    ==== Now masking 600 sec averaged estimate.
    avg dTdz < 3.0e-03 NaN-ed out 0.00% of estimates (0 points)
    |Tz| going below threshold = 1.0e+00 NaN-ed out 0.49% of estimates (283 points)
    max_Kt > 1.0e+00 NaN-ed out 0.00% of estimates (2 points)
    max_Jq > 1.0e+04 NaN-ed out 0.02% of estimates (10 points)
```

**Comment by dcherian** [comment]
This is ready to merge. It adds:

1. more comments in combine_turbulence

2. more informative print statements in combine_turbulence. Now tells you how many 1 sec estimates were NaN before masking.

3. More cautious before applying symmetric log transform (only applied if 30% of data is of opposite sign).

4. Removes a couple of panels from the stratification figure.
histograms-stratification

5. Adds nice titles to combine_turbulence figures (see top left).
histograms-final

**Pull request merged**
